// Generated by Wrangler by running `wrangler types`

interface Env {
	OPENROUTER_BASE_URL: string;
	OPENROUTER_API_KEY: string;
	JWT_SECRET: string;
	POSTGRES_URL: string;
	BRAVE_API_KEY: string;
	PLUNK_API_KEY: string;
	BUCKET_CDN: string;
	BROWSER_URL: string;
	BUCKET: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	BROWSER: Fetcher;
	AI: Ai;
	ASSETS: Fetcher;
}
